name: 'Default Gradle Build'
description: 'build gradle project with default settings'
inputs:
  java-version:
    description: 'JDK version to setup (default "17")'
    default: "17"
    required: false
  java-distribution:
    description: 'JDK distribution to setup (default "temurin")'
    default: "temurin"
    required: false
  targets:
    description: 'Targets to execute (default: "clean test assemble")'
    default: "clean test assemble"
    required: false
  checkout:
    description: 'Implicitly perform checkout'
    default: "true"
    required: false
runs:
  using: "composite"
  steps:
    - name: checkout
      if: ${{ inputs.checkout == "true" }}
      uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
    - name: build, test
      run: ./gradlew --no-daemon --info ${{ inputs.targets }}
      shell: sh
    - name: Upload test reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: build/reports/tests/
